### ISSUE TITLE
Release on pypi

### ISSUE THREAD

**Issue by patrick91** [cuda-networks/django-eb-sqs#11]
There is no release on pypi, would really be handy to be able to install this via pip :)

**Comment by BenjaminWatts** [comment]
No expert - this works for me: pip install git+git://github.com/cuda-networks/django-eb-sqs.git. Can also put it in a requirements.txt fine

**Comment by gililip** [comment]
Cannot install in EB deploy:

> Collecting git+git://github.com/cuda-networks/django-eb-sqs.git (from -r /opt/python/ondeck/app/requirements.txt (line 28))
> Cloning git://github.com/cuda-networks/django-eb-sqs.git to /tmp/pip-4dkMfo-build
> Error [Errno 2] No such file or directory while executing command git clone -q git://github.com/cuda-networks/django-eb-sqs.git /tmp/pip-4dkMfo-build
> Cannot find command 'git'

**Comment by BenjaminWatts** [comment]
you need to install git on the eb instance before you install the python libs - depending which version of linux, then something like `RUN yum install git` - on the Dockerfile

**Comment by gililip** [comment]
We don't use Docker. 
I put this in a config file inside .ebextensions folder:
```
packages:
  yum:
    git: []
```

**Comment by alexeyts** [comment]
Issue resolved, we deployed the library to PyPI
