### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by techdragon** [cuda-networks/django-eb-sqs#13]
Project looks awesome from the readme, but I can't use a project without a License. 
Can the current contributors agree on a License and license the repo.

I'd like to suggest the use of one of the MIT, BSD, or Apache 2.0 licenses. But its obviously up to the current contributors to decide.

Edit:
I'm not a lawyer, but I think, @patrick91 @Schweigi @itaybleier, you will all have to agree on the license.

**Comment by patrick91** [comment]
That's fine by me :)

**Comment by techdragon** [comment]
Thanks for the reply @patrick91, now we just need @Schweigi and @itaybleier to reply.

**Comment by Schweigi** [comment]
We need to clarify the license first with the legal team and will come back to you. Personally I would prefer to put it under MIT.

**Comment by techdragon** [comment]
@Schweigi Thanks for the update. MIT or 2 clause BSD would definitely my preferred choice, but really any permissive license will be good. I know a lot of companies decide on Apache 2.0 and thats that a fine choice too.

**Comment by techdragon** [comment]
@Schweigi Did the legal team provide any indication how long it would take them to clarify the license?

**Comment by techdragon** [comment]
@Schweigi Has there been any progress on resolving this?

**Comment by itaybleier** [comment]
@techdragon - we are in the process of looking into it, hopefully will have an update in the upcoming week. Thank you for your patience.

**Comment by Schweigi** [comment]
@techdragon @patrick91 Added MIT license.
