### ISSUE TITLE
Improvement candidates

### ISSUE THREAD

**Issue by holger-zeit** [cuda-networks/django-eb-sqs#23]
Hi, this project seems super useful!

I'm interested in using it in a production system and have a few minor improvement candidates.
I'd love to hear your feedback and we can have a quick discussion around these points before I jump into implementing anything. If you have other ideas that seem more pressing we can collect them in this thread as well.

Initial ideas:
1. Use CI to run tests on PRs and commits to master: useful as sanity check for commits and discussions about pull requests. Services like TravisCI are free for open-source projects like this
2. Upload project to [PyPI](https://pypi.python.org/pypi) for easier installations via pip
3. Allow explicit setting of credentials (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY) in django settings. If there not given, default to existing behaviour by boto discovering the credentials

Let me know what you think, thanks!

**Comment by alexeyts** [comment]
Hi @holger-zeit,
Thanks for your feedback.
We're using this project in production on a pretty decent scale (for SQS), and would definitely be glad that it serves useful, and gets additional traction.

Regarding your ideas:
1. Definitely would be useful. For our other projects, we use [CircleCI](https://circleci.com/), so we would probably prefer to sue the same for this project. It has a free tier for open source, so I believe we just need to add a `circle.yml` for this project to build (if you have the time, feel free to take a first stab at this).
2. This would be definitely nice to have (we even have the issue #11 for this). But as there's a fairly easy workaround, we preferred not to invest time into this as of yet...
3. This sounds like a pretty straightforward change, so you can just submit a PR on this IMO

Alexey

**Comment by alexeyts** [comment]
2 out of the 3 suggestions were implemented, so will close the issue for now.
Explicitly setting credentials could be contributed easily, feel free to do that if interested.
Thanks
