### ISSUE TITLE
KeyError ['endpoint_resolver'] /worker/process error 

### ISSUE THREAD

**Issue by phillipsmjordan** [cuda-networks/django-eb-sqs#50]
I am sporadically getting a key error when eb_sqs tries to initialize the SQS client (see sentry link below). Possibly related to [this issue](https://stackoverflow.com/questions/52675027/why-do-i-sometimes-get-key-error-using-sqs-client)?

https://sentry.io/share/issue/e36b386c2ea4494aa1145b3557872ad8/

AWESOME work on this project, btw.

**Comment by alexeyts** [comment]
Thanks!

According to the issue this is related to multi-threading, do you use that?
I don't think we really supported that.

Btw, if you're trying to run a worker which processes queues, the I would suggest using `process_queue` management command  instead.
