### ISSUE TITLE
Handing SIGTERM in process_queues() command

### ISSUE THREAD

**Issue by phillipsmjordan** [cuda-networks/django-eb-sqs#51]
After going through the source code, I didn't see anything meant to handle system signals (maybe I missed it). Is there a way to halt reading from the queue but continue processing running tasks? If not, would it be worth trying to handle a SIGTERM, for example, in the main worker loop? 

Loving the project!

**Comment by alexeyts** [comment]
Definitely a good idea. Thanks!
