### ISSUE TITLE
Make it clear that Elastic Beanstalk support was removed

### ISSUE THREAD

**Issue by josh-osiq** [cuda-networks/django-eb-sqs#56]
Hello,

I just spent awhile trying to figure out why the library was no longer working after updating it. I did not realize that elastic beanstalk was no longer supported until I looked through the diffs of the README and saw references to elastic beanstalk were removed. It would be nice if the README made it clear that support was removed.

**Comment by alexeyts** [comment]
Good point.
I added it to the relevant release description.

I don't think the README itself should contain description of obsolete functionality since, as you mentioned, there's version control for that.
